services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - "5432:5432"
    networks:
      - nsos_net

  django:
    build: ../services/api
    working_dir: /app
    ports: 
      - "8000:8000"
    environment:
      - SECRET_KEY=${API_SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${API_ALLOWED_HOSTS}
      - DATABASE_ENGINE=${DB_ENGINE:-postgresql}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - nsos_net
    volumes:
      - static_volume:/app/staticfiles
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/admin/')\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  rag:
    build: ../models # NOTE: move to services/rag
    ports:
      - "8001:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    restart: unless-stopped
    volumes:
      - huggingface_cache:/home/appuser/.cache/huggingface
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health')\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nsos_net


  web:
    build: 
      context: ../services/web
      args:
        NUXT_PUBLIC_API_URL: ${NUXT_PUBLIC_API_URL}
        NUXT_PUBLIC_APP_URL: ${NUXT_PUBLIC_APP_URL}
        NUXT_PUBLIC_RAG_URL: ${NUXT_PUBLIC_RAG_URL}
        NUXT_PUBLIC_FEATURE_FLAG_AI_CHAT: true
        NUXT_PUBLIC_FEATURE_INSTITUTIONS: true
        NUXT_PUBLIC_FEATURE_FLAG_CSV_IMPORT: true
        NUXT_PUBLIC_FEATURE_FLAG_USER_AVATARS: true
    ports:
      - "3000:80"
    environment:
      NODE_ENV: production
      NUXT_PUBLIC_MSW_ENABLED: false
    depends_on:
      django:
        condition: service_healthy
      rag:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - nsos_net

networks:
  nsos_net:
    driver: bridge

volumes:
  huggingface_cache:
  dev_postgres_data:
  static_volume:

