services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"
    networks:
      - nsos_net

  django:
    build: ../services/api
    working_dir: /app
    ports: 
      - "8000:8000"
    environment:
      - SECRET_KEY=${CORE_API_SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${CORE_API_ALLOWED_HOSTS}
      - DATABASE_ENGINE=${DB_ENGINE:-postgresql}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - nsos_net
    volumes:
      - static_volume:/app/staticfiles

  rag:
    build: ../models # NOTE: move to services/rag
    ports:
      - "8001:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - huggingface_cache:/home/appuser/.cache/huggingface
    networks:
      - nsos_net


  web:
    build: ../services/web
    ports:
      - "3000:80"
    environment:
      NODE_ENV: production
      NUXT_PUBLIC_API_URL: http://django:8000
      NUXT_PUBLIC_MSW_ENABLED: false
    depends_on:
      - django
    restart: unless-stopped
    networks:
      - nsos_net

networks:
  nsos_net:
    driver: bridge

volumes:
  sqlite_data:
  huggingface_cache:
  dev_postgres_data:
  static_volume:

